### ISSUE TITLE
Smoke test CudaEnabledTest failed on s390 and aarch64 with openj9

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/temurin-build#2578]
Smoke test CudaEnabledTest failed on s390 and aarch64 with openj9

```
22:46:27  [CudaEnabledTest] [INFO] Starting test to see if CUDA functionality is enabled in this build.
22:46:27  FAILED: testIfCudaIsEnabled
22:46:27  java.lang.AssertionError: Cuda should be enabled on this build, but we found no evidence that this was the case.
22:46:27  	at org.testng.Assert.fail(Assert.java:96)
22
```
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-openj9_SmokeTests/4/console
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-s390x-openj9_SmokeTests/4/console

Tests find libj9prt.so and read the file. If file contains 'cudart' test pass, otherwise fail.

Is this expected for s390 and aarch64? @AdamBrousseau @keithc-ca

**Comment by keithc-ca** [comment]
There are a number of problems with that test:
* it doesn't look in the `compressedrefs` directory, which would be appropriate for a non-mixedrefs build
* it isn't discriminating enough - it might look in `libj9prt.debuginfo` instead of `libj9prt.so`
* it assumes the build being tested was configured with `--enable-cuda`, which isn't appropriate for s390x and perhaps isn't the case for the aarch64 build

What is the test trying to accomplish?

**Comment by adamfarley** [comment]
The test is supposed to find that file and locate that string within the file.

It seems the test has somehow "lost" the logic whereby it is only run on the right platforms (Windows, xLinux, and pLinux). Maybe that logic was replaced by something else, and that "something else" needs tweaking.

I think we need a general upgrade for the test, covering the fundamental issue here, the points Keith raised and also handling [this failure](https://trss.adoptopenjdk.net/output/test?id=607c13f547db9757311be35d) on xLinux.

Will handle that in a few minutes, once I'm done with another task.

**Comment by adamfarley** [comment]
Ok, I think we've tackled all the problems. Here's a few test runs:

jdk16 - https://ci.adoptopenjdk.net/job/Grinder/257/console
jdk11 - https://ci.adoptopenjdk.net/job/Grinder/265/console
jdk8 - https://ci.adoptopenjdk.net/job/Grinder/273/console
jdk8 Windows - https://ci.adoptopenjdk.net/job/Grinder/281/console

Note: jdk8 Windows had to be run again because we lost our connection to the windows test machine in the first batch.

Also note: Some of the other smoke tests failed, but no instance of the cuda test failed. I read all the outputs to verify that they passed, and that we're looking for the cuda string (or the absence of same) on the correct platforms.

Creating a PR now. To be merged after the release.

**Comment by sophia-guo** [comment]
> it doesn't look in the compressedrefs directory, which would be appropriate for a non-mixedrefs build

Looks like openj9 doesn't have non-mixedrefs build?
https://www.eclipse.org/openj9/docs/version0.25/#single-build-for-compressed-references-and-non-compressed-references

**Comment by keithc-ca** [comment]
We don't regularly create non-mixedrefs builds, but the test shouldn't break if applied to such a build.
