### ISSUE TITLE
Smoke test testJFRAvailable failed with jdk11 aix hotspot

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/temurin-build#2582]
Smoke test testJFRAvailable failed with jdk11 aix hotspot

```
03:34:30  FAILED: testJFRAvailable
03:34:30  java.lang.AssertionError: Expected JFR to be present but it is absent. expected [0] but found [1]
03:34:30  	at org.testng.Assert.fail(Assert.java:96)
03:34:30  	at org.testng.Assert.failNotEquals(Assert.java:776)
```
https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-aix-ppc64-hotspot_SmokeTests/5/console

JDK Flight recorder was added to JDK 11 (JEP 328) and backported to JDK 8u262.
https://openjdk.java.net/jeps/328
https://bugs.openjdk.java.net/browse/JDK-8223147

**Comment by sophia-guo** [comment]
Thanks @karianna for confirm that JFR is not supported on PPC AIX

https://wiki.openjdk.java.net/pages/viewpage.action?pageId=13041681. 

Test should be disabled for AIX.

**Comment by adamfarley** [comment]
@sophia-guo - Heya, I've created a small PR for this. Rather than excluding the test on AIX, I recommend running the test, but removing the expectation that we'll find a functional JFR.

See [this PR](https://github.com/AdoptOpenJDK/openjdk-build/pull/2599) for an example of what I mean. I'd appreciate your thoughts when you have time. :)
