### ISSUE TITLE
Upgrade jdk17+ linux builds to use gcc-8

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#2787]
Upstream OpenJDK supported build platforms for jdk-17+ is gcc 8.2.1.
There are also features available in gcc-8 that are advantageous/required for "reproducible builds".

**Comment by sxa** [comment]
Overall building doc mentions 10.2: https://github.com/openjdk/jdk17u/blob/master/doc/building.md#gcc
The OpenJDK wiki lists gcc 8.2.1 for OpenJDK 17: https://wiki.openjdk.java.net/display/Build/Supported+Build+Platforms

The PMC had a discussion on this and we agree that moving forward with using GCC8.2.1 for Temurin-17 is a good move.

**Comment by sxa** [comment]
Right ... I've done some more investigation ... GCC 8.2.1 was a Red-Hat specific branch (albeit in the official GCC repository, although you have to jump through some hoops to find it). On that basis I'd personally be slightly reluctant to use that one since it was never a formal GCC release. Here is what I believe other distributions are using:

JDK17 Distribution | GCC version
--- | ---
Adoptium | 7.5.0
Azul | 7.3.1
Bellsoft | 7.3.1
Corretto | 7.3.1
Oracle | 10.3.0

So we're already ahead of all the others apart from Oracle. I believe Red Hat uses 8.5 for theirs. So unless we went bleeding edge we could use:
- 8.2.1 despite it not being an official release from GCC as [it's listed in the wiki](https://wiki.openjdk.java.net/display/Build/Supported+Build+Platforms)
- 8.5 as the latest in the 8 line
- Latest 9.x (Alibaba Dragonwell are keen to use 9 over earlier versions for performance reasons, but we don't have to use the same version for Temurin!)
- 10.2 which would match [the version listed in the source code](https://github.com/openjdk/jdk17u/blob/master/doc/building.md#gcc) (or go for a later 10 as Oracle have done!)
- Go bleeding edge ([11.2 at the time of writing this](https://gcc.gnu.org/releases.html)). I wouldn't choose this personally

**Comment by sxa** [comment]
Posted question on GCC versions to `jdk-dev` at https://mail.openjdk.java.net/pipermail/jdk-dev/2021-December/006299.html

**Comment by sxa** [comment]
There was no response to this. My gut feel is now to go with 10.2 (or maybe 10.3?)

**Comment by karianna** [comment]
Might as well push to 10.3 in that case

**Comment by sxa** [comment]
Actually retracting what I said earlier I've just seen (it wasn't threaded correctly), but there have now [been updates to the wiki](https://mail.openjdk.java.net/pipermail/jdk-dev/2022-January/006310.html) to list 10.3 instead of the earlier one now, so I'm going to assume 10.3 too 👍🏻
