### ISSUE TITLE
How do I build a specific version?

### ISSUE THREAD

**Issue by darkedges** [adoptium/temurin-build#2817]
I am confused by how to build a speicific version. For example jdk-11.0.13+8

I have found that I can build via a the release branch of tag jdk-11.0.13+8_adopt, 

```
./makejdk-any-platform.sh \
    -J /usr/lib/jvm/java-10-openjdk \
    --build-variant hotspot \
    --configure-args \
    --disable-warnings-as-errors \
    --tag jdk-11.0.13+8_adopt \
    --branch release \
    jdk11u
```

but when I look at the version it comes with a `beta`

```
openjdk 11.0.13-beta 2021-10-19
OpenJDK Runtime Environment Temurin-11.0.13+8-202112252131 (build 11.0.13-beta+8-202112252131)
OpenJDK 64-Bit Server VM Temurin-11.0.13+8-202112252131 (build 11.0.13-beta+8-202112252131, mixed mode)
````

I have tried various build `build-number` and `version-number` arguments but I don't seem to be able to get close.

Would it be possible to make the documentation clearer with an example of how to get a specific version built.

**Comment by sxa** [comment]
Hi, thanks for raising the issue :-)

Use the `--without-version-pre --without-version-opt` configure parameters to remove the `beta` designation. https://github.com/adoptium/temurin-build/issues/2671 will be able to clear up some of the confusion relating to the `_adopt` tag too (but it's taking me a while to find the time to get round to implementing it!) Our scripts are currently always producing something badged as Temurin, so we wouldn't want to make a non-beta the default for user-generated ones in order to avoid confusing with the "Official" Temurin builds. One of the disadvantages of doing everything in a fully open source way - we make it too easy to make something that looks identical to ours ;-)

The `without-version` ones are listed in https://github.com/adoptium/temurin-build/blob/master/RELEASING.md but that's generally for people running through the quarterly release process using the Adoptium infrastructure. While we could add the information on that into the main building instructions I'd be a little reluctant to do it until we've implemented the HotSpot/Temurin split in order to avoid the confusion mentioned in the end of the previous paragraph, but I'll add a note into that issue to remind me to update that in the docs too once it's done. Thanks for your feedback on this.

Hope those parameters help. If you find they don't, please re-open this issue.
