### ISSUE TITLE
Propose to enable GitHub new feature "Default to PR titles for squash merge commit messages"

### ISSUE THREAD

**Issue by zdtsw** [adoptium/temurin-build#2934]
Propose: 
Enable GitHub PullRequest feature [Default to PR titles for squash merge commit messages](https://github.blog/changelog/2022-05-11-default-to-pr-titles-for-squash-merge-commit-messages/)

Reason: 
When we have too many commits for one PR, by default, all commits squash into one final commit when they get merged.
Normally the first commit is used as the final commits message and others are appended for detail.
In most case, this is fine, but if commits are used for debug, testing, etc, especially rebase branch (take in new commits from default-branch) can be messy for the final commit. A bad example: https://github.com/adoptium/temurin-build/commit/586d2480b39ae7922ad29dfe519c4389299c185f
To enable this feature (which does not enforce to only use PR titles), it could tidy up our commit history, allow us to have only useful information in the final commit before it is merged to default-branch.

**Comment by sxa** [comment]
I'm personally 👎🏻 on this. I quite often set the PR title separately and I think it's generally good practice for people to explicitly set the commit message correctly so I'm likely to end up changing the defaults a lot of the time where I didn't need to previously, but if there's enough enthusiasm elsewhere for changing this I won't block it.

Personally if I have multiple 'fixup' commits in a PR I'd squash them when I push them up to the PR (Although admittedly that has the disadvantage that it's not so obvious to reviewers what you've changed). Usually if I'm merging a PR I'll try and trim that down, but I appreciate that this change would remove that need.

What happens if you've used a multi-line commit message? Does it get replaced with the PR summary title (which would be undesirable and potentially not obvious to the person doing the merge)

**Comment by zdtsw** [comment]
Right. Since I do not have "merge" permission yet, it is difficult for me to guess what I can do (update final commit title, message etc ) before click "Squash and Merge" button. 
But if it is something already available (without enable this feature), I am happy to leave the setting as-is.

**Comment by zdtsw** [comment]
> Took me a while to find an example I could screenshot that had been approved and not merged but here's one from the PR at [adoptium/infrastructure#2544](https://github.com/adoptium/infrastructure/pull/2544) - after I click the "squash and merge" button it gives me the chance to edit the full commit message: ![image](https://user-images.githubusercontent.com/6487691/169015444-7c6419ab-4836-4199-8638-403fc2a8560b.png)

Cool!  I think I am fine with what we have now

**Comment by zdtsw** [comment]
close this issue for now.
