### ISSUE TITLE
Build from source for older build broken

### ISSUE THREAD

**Issue by nerd2ninja** [adoptium/temurin-build#3062]
Thank you for reporting a broken build! Please fill in the following details:
- Checking and downloading Alsa dependency
Checking for ALSA
downloadFile: Saving url to alsa-lib.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  966k  100  966k    0     0  2033k      0 --:--:-- --:--:-- --:--:-- 2033k
Using bundled Freetype
Could not find a valid openjdk git repository at /home/human_action/Programs/temurin-build/workspace/build/src so re-cloning the source to openjdk
git clone --depth=1 https://github.com/openjdk/18.0.1+10.git /home/human_action/Programs/temurin-build/workspace/./build//src
Cloning into '/home/human_action/Programs/temurin-build/workspace/./build//src'...
fatal: unable to access 'https://github.com/openjdk/18.0.1+10.git/': The requested URL returned error: 400

- Which platforms (OS+arch) are affected: Raspbian OS Raspberry pi 3 amd-64 cpu
"./makejdk-any-platform.sh -J /usr/lib/jvm/jdk-xx --build-variant hotspot jdk" => command works and installs newest version
"./makejdk-any-platform.sh -J /usr/lib/jvm/jdk-xx --build-variant hotspot jdk --build-number 18.0.1+10" => command returns:
"fatal: unable to access 'https://github.com/openjdk/18.0.1+10.git/': The requested URL returned error: 400"

**Comment by karianna** [comment]
@nerd2ninja can you post the command you used to execute the build?

**Comment by nerd2ninja** [comment]
"./makejdk-any-platform.sh -J /usr/lib/jvm/jdk-xx --build-variant hotspot jdk --build-number 18.0.1+10"

**Comment by sxa** [comment]
> "./makejdk-any-platform.sh -J /usr/lib/jvm/jdk-xx --build-variant hotspot jdk --build-number 18.0.1+10"

Two things here:
1. The `jdk` parameter should be 

Switch the parameters around - the repository name "`jdk`" in your case - needs to go at the end. Also you should use the repository name appropriate for the version you're trying to build, so change that `jdk` for `jdk18u`. The following command should do what you want (although I tend to use `--tag` instead of `--build-number`). It looks like there's a bug in that use case where JAVA_FEATURE_VERSION isn't being set, so this command should work for what you're looking for:

```
JAVA_FEATURE_VERSION=18 ./makejdk-any-platform.sh -J /usr/lib/jvm/jdk-xx --build-variant hotspot --build-number 18.0.1+10 jdk18u
```
Feel free to re-open if that doesn't work for you.
