### ISSUE TITLE
Windows ia64 build

### ISSUE THREAD

**Issue by Qiangong2** [adoptium/temurin-build#3069]
**Problem description:**
This may be an odd question, but how would I build an eclipse temurin build for Windows for Itanium? Specifically Windows Server 2008 R2. I know that openjdk 8 has source code for Windows ia64, I just can't find a "simple" way to compile it. Unless I'm missing something, it doesn't look like eclipse temurin supports it.

**Comment by sxa** [comment]
Wow there's a question I didn't expect! The project does not have any Itanium hardware, now any easy way to obtain it. In principle I would expect that it wouldn't be too hard if the prerequisite packages were available - which may be easier if you've got the software to let you run x64-32/ia32 code on your system. It would need cygwin or similar to be available, and while they did have a 32-bit version last time I checked it was marked as "not recommended" :-)

Obviously, given the above, we are unable to offer any particular support for it and the demand would realistically be too low for us to do so. What problems did you come across when trying? In principle I would expect that if you had a suitable compiler and the code is still in the JDK8 codebase you should be able to build it as normal.

If you want to try it yourself, our wrapper script `makejdk-any-platform.sh` probably won't work (Although it might...) but take a look at the log in https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-windows-x64-hotspot/1227/consoleFull for an example of what an x64 build looks like. In particular the downloading of freetype and the `./configure` line (you probably don't need all of the options we include). It's roughly speaking a normal "configure; make" process once you've got all the bits in place. You need an existing JDK7 or JDK8 as a "boot JDK" in order to build the JDK.

**Comment by Qiangong2** [comment]
Mainly the issue I'm having is getting to a buildable state. Unless I'm missing something, compiling for ia64 windows can only be done with Visual Studio 2010, which openjdk supposedly supports. However, I can't seem to build out an sln file.

It's entirely possible I'm misreading the requirements though, but it was my understanding that to build openjdk, you need cmake. cmake doesn't support ia64 windows from what I can find. There are ia64 files present in openjdk 7 and 8, so it _should_ be possible right?

**Comment by sxa** [comment]
Openjdk itself should not require cmake to build (Curious as to where you saw that - was it in our docs or upstream openjdk?)
We've only been building on VS2013 and later recently so I can't confirm if that really does still work. (The OpenJ9 project now uses cmake by default, but the hotspot builds do not need it)

**Comment by Qiangong2** [comment]
Oh, maybe it was OpenJ9 I was seeing then. I know it's preferable to build on the platform you're deploying on, but ia64 doesn't actually have compilers (for windows) that run on the device. You need to cross-compile from an x86 devices, which may be where I'm running into issues.

Since there's no cross-compile support in mingw for ia64, the docker build script wouldn't function right?
