### ISSUE TITLE
Auto trigger release pipeline builds once "-ga" tag is published

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#3167]
To save missed time before we notice the "-ga" tags.. we should have a "monitor" that triggers the release-pipeline jobs:
1. Once a -ga tage appears, eg.jdk-19.0.2-ga, query the actual build tag on the same commit (eg.jdk-19.0.2+n)
2. Launch the already generated Jenkins release-pipline job (already branched from temurin-build,.. tag), specifying the actual release jdk tag...

**Comment by zdtsw** [comment]
currently all mirror jobs are under https://ci.adoptopenjdk.net/view/git-mirrors/job/git-mirrors/job/adoptium/, 
thinking if easier to either extend this job, or add function into `skaraMirror.sh`

**Comment by zdtsw** [comment]
> currently all mirror jobs are under https://ci.adoptopenjdk.net/view/git-mirrors/job/git-mirrors/job/adoptium/, thinking if easier to either extend this job, or add function into `skaraMirror.sh`

so to keep things simple, we will keep what is in these mirror jenkins job, and create new job for the trigger part

**Comment by zdtsw** [comment]
One option is: using gihub jenkins plugin, by adding webhook in source code repo (e.g https://github.com/adoptium/jdk17u)
![Screenshot from 2022-11-30 17-34-23](https://user-images.githubusercontent.com/915053/204855320-1777e6cf-881a-42c6-8118-deb38ffb1216.png)
then we can, in the release pipeline, get tag's name from payload to fill in `scmReference`

**Comment by smlambert** [comment]
In case you want an approach that is not tied to Jenkins/plugins or implies Jenkins config that is not visible to all, here is a snippet from a shell script used to autogenerate the scorecard, dumps all tags for a repo into a file, and could be adapted to check for existence of one.

```
TAG_INFO=tag${VERSION}.txt

function getrepo () { 
    REPONAME=$1
    REPO=$2
    PREFIX=$3
    DIR=$(pwd) 
    echo "Repo is  $REPO"  
    rm -rf $REPONAME
    git init $REPONAME
    cd  $REPONAME
    echo "Getting Tags for $REPONAME"
    git config extensions.partialClone true
    git remote add origin https://github.com/adoptium/$REPONAME
    git fetch --filter=blob:none --tags --depth=1 origin   2>&1 | cat > /dev/null  
    git log --tags --simplify-by-decoration --pretty="format:%ci %d" > ../${PREFIX}$TAG_INFO
    cd .. 
    git config extensions.partialClone false
    rm -rf $REPONAME 
}

if [ $VERSION == 8 ]
then
    REPONAME=aarch32-jdk8u
    getrepo $REPONAME https://github.com/adoptium/$REPONAME  "aarch32-jdk8u-"
fi
REPONAME=jdk${VERSION}u  
getrepo $REPONAME https://github.com/adoptium/$REPONAME 

```

**Comment by zdtsw** [comment]
so sum how we are doing release with tags now: (take 2022 oct jdk19 as example)
- in skara  repo openjdk/jdk19u, 
  - first creates commit by upstream contributor
  - when it is the release date, normal build tag is applied  to this commit `jdk-19.0.1+10`
  - later to apply GA tag `jdk-19.0.1-ga` onto the same commit : `jdk-19.0.1+10` and `jdk-19.0.1-ga` are pointed to the same sHA1
- in origin  repo adoptium/jdk19u
  - git-mirror job checks per hour if new tag appear then create our adoptium tag `jdk-19.0.1+10_adopt` (this is done all the time regardless release or not) onto the same `jdk-19.0.1+10`
  - the person drives release, checks mail/slack/etc if we have `jdk-19.0.1-ga` appeared and use `jdk-19.0.1+10_adopt` as scmReference to start openjdk19-pipeline.

So in theory, use any of these 3 tags `jdk-19.0.1+10`  `jdk-19.0.1-ga` and `jdk-19.0.1+10_adopt` to build are the same.
But we should stick with `jdk-19.0.1+10_adopt` for our release.

for this issue, i think the real automation, we should do is not to use "-ga" tag (i.e `jdk-19.0.1-ga`) but `jdk-19.0.1+10_adopt`

and due to the difficulty of troubleshooting events by github jenkins plugin in ci.adoptopenjdk.net ( without proper permission, even event-driven model is much better in this use case), I will start with a solution purely using git cli.

**Comment by zdtsw** [comment]
```
# fetch all new refs including tags
git fetch --all --tags

# take latest -ga tag (sorted by time) from skara as input
gaTag=`git tag --sort=-v:refname | grep ga | head -1`

# from -ga tag find original commit SHA and list all tags applied onto it , exclude -ga tag and append _adopt
scmReference=`git rev-list -1 $gaTag | xargs git tag --points-at  | grep  -v  '\-ga'`_adopt

# loop with 10m sleep not git-mirror has not apply _adopt tag or merge conflict in git-mirror need to manual resolve
for i in {1..5}
do
  if [ $(git tag -l "$scmReference") ]; then
    echo $scmReference
    break
  else
    echo "No $scmReference found yet, sleep 10minutes"
    sleep 10m
  fi
done

echo "Trigger release pipeline"
...
```

**Comment by zdtsw** [comment]
Now i realize one more thing:
so the release pipeline is built based on all parameters are the same, i.e no drift from one jdk version to another version.

But in some case, we need to set a different value
e.g `--with-toolchain-version=2013` for jdk8 win64 , others no need this flag (need double check `--with-toolchain-version=2017 `on jdk11 win64)
e.g `overridePublishName` is needed for jdk8 arm32
e.g `--without-version-pre --without-version-opt `is needed for jdk11, 17 and 19 (probably can use this as pre-set default when create release pipeline)

**Comment by zdtsw** [comment]
so i think it is better, that we do not trigger jdk8u aarch32 automatically and it is usually coming with late ga tag.

**Comment by zdtsw** [comment]
as for the others, release champion can do a double check after release pipelines are generated, and correct parameters if they need customized value. e.g `additionalConfigureArgs`
