### ISSUE TITLE
SBOM tool dependency download sometimes fails causing SBOM generation failure

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#3315]
https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x86-32-temurin/208/console

Sometimes the download files due to a network glitch, eg:
```
20:51:15  download-jackson-databind:
20:51:15       [echo] Downloading jackson-databind version 2.14.2
20:51:15       [echo] Executing macro download-file
20:51:15       [echo] File to download: https://search.maven.org/classic/remotecontent?filepath=com/fasterxml/jackson/core/jackson-databind/2.14.2/jackson-databind-2.14.2.jar
20:51:15       [echo] Destination: build/jar/jackson-databind.jar
20:51:15       [echo] Download tool: curl
20:51:15       [exec]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
20:51:15       [exec]                                  Dload  Upload   Total   Spent    Left  Speed
20:51:15       [exec] 
20:51:16       [exec]   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:06 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0100   122  100   122    0     0     16      0  0:00:07  0:00:07 --:--:--    29
```

The download needs to be more resiliant to these failures.

Such failures causes the SBOM generation to fail with:
```
20:51:19  Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/AnnotationIntrospector
20:51:19  	at org.cyclonedx.BomGeneratorFactory.createJson(BomGeneratorFactory.java:65)
20:51:19  	at temurin.sbom.TemurinGenSBOM.generateBomJson(Unknown Source)
20:51:19  	at temurin.sbom.TemurinGenSBOM.writeJSONfile(Unknown Source)
20:51:19  	at temurin.sbom.TemurinGenSBOM.main(Unknown Source)
20:51:19  Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.AnnotationIntrospector
20:51:19  	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
20:51:19  	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
20:51:19  	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
20:51:19  	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
20:51:19  	... 4 more
```

**Comment by smlambert** [comment]
May want to consider adding it to a build.getDependency job, so that it can be pulled from a ci.adoptium.net job's latest successful artifacts instead of an external resource.

We found this greatly improved stability of test jobs that require dependencies (tests reference https://ci.adoptium.net/view/all/job/test.getDependency/ to pick up 'last successful artifacts' which is updated sufficiently often / daily).

**Comment by zdtsw** [comment]
several options:
1. as Shelley mentioned, to use the same job download and catch in the job workspace
2. since the version of these dependencies are fixed in build.xml https://github.com/adoptium/temurin-build/blob/master/cyclonedx-lib/build.xml#L23-L33 , we can safely use https://ci.adoptium.net/userContent/ to store these dependency jar files. 
3. add `<retry count="5" delay="5000">` in the build.xml around the download-file

**Comment by adamfarley** [comment]
> May want to consider adding it to a build.getDependency job,

Good idea. Will have a go.

**Comment by adamfarley** [comment]
Ok, changes made, pending merge.

New job: https://ci.adoptium.net/view/all/job/build.getDependency/

PR: https://github.com/adoptium/temurin-build/pull/3462

Test run: https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-mac-x64-temurin/348/console

**Comment by adamfarley** [comment]
Ok, all merged and resolved. Closing issue.
