### ISSUE TITLE
20.0.1+9 misses linux ppc build

### ISSUE THREAD

**Issue by bernt-matthias** [adoptium/temurin-build#3371]
while working on an update of the conda-forge openjdk build I noticed that apparently [jdk-20.0.1+9](https://github.com/adoptium/temurin20-binaries/releases/tag/jdk-20.0.1%2B9) misses the linux ppc build.

maybe I'm wrong.

**Comment by sxa** [comment]
Unfortunately you are correct - Linux/ppc64le, Linux/s390x, Linux/arm32 and AIX/ppc64 are not currently available for JDK20 due to testing issues our of Adoptium's control. We currently expect this to be rectified for JDK21 later in the year. However you can still download nightly builds of JDK20 (and 21) if required. on those platforms.

**Comment by bernt-matthias** [comment]
Thanks for the prompt reply and clarification.
