### ISSUE TITLE
Windows UCRT Redist DLL version is not deterministic

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#3479]
The openjdk make/autoconf logic correctly finds the VS2022 vcruntime location. But the UCRT logic finds the “Windows Retail location”, which I think depends on the particular Windows you have installed, and when you installed it, or possibly the first VS you may have installed.
This means we are not distributing a managed version of the UCRT, rather whatever happens to be in the Windows Kits\10\Redist standard retail location on the particular build machine.

**Comment by tellison** [comment]
Although it is true that 
> we are not distributing a managed version of the UCRT, rather whatever happens to be in the Windows Kits\10\Redist standard retail location on the particular build machine.

We do manage the Windows OS images that are used on build machines, so it indirectly influences which runtime libraries will be packaged. That said, since they are part of our product redistributable I think it would be preferable to explicitly define them in the OS install and build configuration.
