### ISSUE TITLE
All Linux binaries missing from latest release in temurin17-binaries

### ISSUE THREAD

**Issue by szynalr-uki** [adoptium/temurin-build#3581]
**What are you trying to do?**
We have an automated build which gets the latest Linux JRE binary and builds an internal container image. The latest build of Temurin 17 (On October 27th) only has Windows binaries.
https://github.com/adoptium/temurin17-binaries/releases/tag/jdk-17.0.9%2B9.1

**Expected behaviour:**
Non-Windows binaries to be present in release

**Observed behaviour:**
Non-Windows binaries missing from release

**Any other comments:**

**Comment by sxa** [comment]
You should not be pulling directly from that location in general - if at all possible please use the API to retrieve the latest code for your platform.

The `.1` version was a respin to fix a Windows specific problem which is why that is the only one in that release. This is mentioned in the "Windows Binary Respin" section of the [release announcement blog](https://adoptium.net/blog/2023/11/eclipse-temurin-8u392-11021-1709-and-2101-available/)

**Comment by szynalr-uki** [comment]
Ah, I have found the [API cookbook page](https://github.com/adoptium/api.adoptium.net/blob/main/docs/cookbook.adoc#example-two-linking-to-the-latest-jdk-or-jre). This should have the answers.

Apologies for not reading the manual. 🤦
