### ISSUE TITLE
Wrong folder name in published MacOS x64 builds of static libraries for 23-EA  

### ISSUE THREAD

**Issue by zakkak** [adoptium/temurin-build#3602]
**What are you trying to do?**

[Build Mandrel using Temurin 23 EA builds](https://github.com/graalvm/mandrel-packaging/pull/384#issuecomment-1881700810) with static libs downloaded from https://github.com/adoptium/temurin23-binaries/releases/download/jdk-23%2B4-ea-beta/OpenJDK-static-libs_x64_mac_hotspot_ea_23-0-4.tar.gz

**Expected behaviour:**

Static libraries should be placed under `lib/static/darwin-amd64` and the build should pass.

**Observed behaviour:**

Static libraries are placed under `lib/static/darwin-arm64` instead and the build fails.

**Any other comments:**

Despite the folder naming the static libraries appear to target amd64.
Renaming the directory in the local installation resolves the issue.

**Comment by Haroon-Khel** [comment]
That does seem likely to be the cause.

Looks like the path name is decided here
https://github.com/adoptium/temurin-build/blob/a352e0845b16c79e04d3a913d2a304aec18c7681/sbin/build.sh#L1329

**Comment by adamfarley** [comment]
Taking a look. :)

**Comment by adamfarley** [comment]
**Working out**

Ok, osArch is set by the BUILD_CONFIG parameter OS_ARCHITECTURE, which is set to "arm64" (even on x64 builds), like Haroon suggested.

OS_ARCHITECTURE is set by the temurin-build config_init.sh script, which sets it to the "arch" parameter.

config_init.sh inherits parameters from makejdk_any_platform.sh

The temurin-build readme specifies arch as:

"This tag identifies the architecture the JDK has been built on and it intended to run on."

This conflates the build platform and the runtime platform, causing our headache.

(BUILD_FULL_NAME seems to do the same thing, and we do that to ourselves from OS_ARCHITECTURE in configureBuild.sh)

So, yeah, hmm. Solving this problem in a cheap, hacky way seems simple, but I want to be sure there's not an underlying problem here.

**Comment by adamfarley** [comment]
@Haroon-Khel 

There seem to be several issues coming out of this, which are likely an issue each. Please review and let me know your thoughts:
- Any thoughts on why we're generating static libs if we don't value it enough to test it?
- We're conflating (mistakenly combining) the target OS and the build/host OS, in several places, mainly:
  - In the SBOM (OS architecture) we use the build OS when we should use the target OS.
  - In config_init, we set the "OS_ARCHITECTURE" to the "uname -m" output, and then we use it as the target architecture in at least a few places. Which prevents a clean crosscompilation.
- The code has BUILD_CONFIG[OS_ARCHITECTURE], ARCHITECTURE, MACHINEARCHITECTURE, arch, and more! We should just have two global values (target and build), to prevent this headache in the future.

**Comment by jerboaa** [comment]
> * Any thoughts on why we're generating static libs if we don't value it enough to test it?

Static libs are mostly used by GraalVM builds. GraalVM is based on LabsJDK (a OpenJDK fork). Mandrel is based on OpenJDK (vanilla). So we raised this issue since we build mandrel with it in the [mandrel-packaging](https://github.com/graalvm/mandrel-packaging) PR checker. So we notice eventually. As we did and filed the issue.

**Comment by jerboaa** [comment]
This seems to be a problem for JDK 21, JDK 22 and JDK 23 builds.

**Comment by adamfarley** [comment]
This issue has now been resolved. Correctly-named ea versions of static libs can be found here: 
- [jdk21](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk21u/job/jdk21u-mac-x64-temurin/lastSuccessfulBuild/artifact/workspace/target/) - Next release version in April.
- [jdk22](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk22/job/jdk22-mac-x64-temurin/lastSuccessfulBuild/artifact/workspace/target/) - Next release version in March.
- [jdk23](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk/job/jdk-mac-x64-temurin/lastSuccessfulBuild/artifact/workspace/target/) - Next release version in September.

The fix resolving this issue in the short term can be found here: https://github.com/adoptium/temurin-build/pull/3619
The long-term fix will be worked on here: https://github.com/adoptium/temurin-build/issues/3648

Closing this issue.

**Comment by adamfarley** [comment]
All builds produced by Adoptium frameworks from this point onwards should contain this fix.

**Comment by jerboaa** [comment]
> All builds produced by Adoptium frameworks from this point onwards should contain this fix.

Thanks for the info.

**Comment by sxa** [comment]
Perhaps we should add this to the [release blog](https://adoptium.net/blog/2024/01/eclipse-temurin-8u402-11022-1710-and-2102-available/)?

**Comment by jerboaa** [comment]
> Perhaps we should add this to the [release blog](https://adoptium.net/blog/2024/01/eclipse-temurin-8u402-11022-1710-and-2102-available/)?

In what way? As a known issue?

**Comment by sxa** [comment]
> > Perhaps we should add this to the [release blog](https://adoptium.net/blog/2024/01/eclipse-temurin-8u402-11022-1710-and-2102-available/)?
> 
> In what way? As a known issue?

Yep and one that we're acknowledging and it will be fixed in the next release (or the ea/nightlies for anyone interested)
