### ISSUE TITLE
Including CRac for container image

### ISSUE THREAD

**Issue by liangyuanpeng** [adoptium/temurin-build#3604]
Features that impact the whole project (e.g. Adding a new OpenJDK distribution) are made over at the [adoptium repository](https://github.com/adoptium/adoptium/).

Otherwise, please describe what enhancement you would like to see in the build scripts:

I'm follow the https://foojay.io/today/springboot-3-2-crac/ with temurin jdk to work for CRac, and it's failed. 

```shell
Unrecognized VM option 'CRaCCheckpointTo=/tmp/tmp_checkpoint'
```

I think the reason is temurin jdk have not include the CRac, and i'm using the container image of eclipse-temurin:21.0.1_12-jdk.

It's the useful feature, could you please build the jdk of including the CRac? Thanks.

**Comment by liangyuanpeng** [comment]
Since I'm using containers, I'm not sure if I should reopen the issue at https://github.com/adoptium/containers ,I will move to this if needed.

**Comment by liangyuanpeng** [comment]
more info:

- https://foojay.io/today/introducing-the-openjdk-coordinated-restore-at-checkpoint-project/
- https://github.com/CRaC/openjdk-builds/releases/

Is it possible for temurin to build a JDK that includes a CRac version?

**Comment by sxa** [comment]
This was discussed in the PMC call today. The outcome was that since CRaC is not yet a stable part of the main openjdk codebase we would not be comfortable shipping it at Adoptium at this time unfortunately.

Until that changes, you cold download a build with CRaC from one of the following OpenJDK providers:
- https://www.azul.com/products/components/crac
- https://bell-sw.com/libericajdk-with-crac (You will note that this page says "Please note that it is based on new UNTESTED technology")

**Comment by liangyuanpeng** [comment]
Thanks for quickly reply. :)
