### ISSUE TITLE
Update Temurin linux builds to use suggested Security Audit gcc compiler flags

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/temurin-build#3685]
The Adoptium security audit outlined some suggested compiler flags for enhanced security, we need to look at evaluating those, and implementing and testing their use.

As part of the Eclipse Adoptium security audit, the following gcc options were suggested as being used to enhance the security of the JDK binaries.
**Code generation suggestions:**
- -fstack-protector-strong : Extends the basic stack protection without impacting all functions, see: https://lwn.net/Articles/584225/
- --param=ssp-buffer-size=4 : [param](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-param) The minimum size of buffers (i.e. arrays) that receive stack smashing protection when -fstack-protector is used. This ties in with -fstack-protector-strong to better cover the stack protection.

**Compiler Warning suggestions:**
- -Wformat : printf/scanf string checks
- -D_FORTIFY_SOURCE=2 : string related compile time checks
- -Wformat-security : enahnced printf/scanf string security checks
- -Wshadow : warn about variable/function shadowing
- -Wconversion : Warn for implicit conversions that may alter a value

**Comment by sxa** [comment]
Builds of jdk-22+35 (Not the GA level!) with a bunch of options. Note that while there are a lot of links in here and the builds are being retained for now this is purely as a convenience while they are being tested and they will not be retained in the future.

Architecture | Options set | AQA Result | Perf result
---|---|---|---
[x64](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk22/job/jdk22-linux-x64-temurin/38/artifact/workspace/target/OpenJDK22U-jdk_x64_linux_hotspot_2024-03-19-15-48.tar.gz) | 1 | [TBC](https://ci.adoptium.net/job/AQA_Test_Pipeline/226/) [s/o](https://ci.adoptium.net/job/Test_openjdk22_hs_sanity.openjdk_x86-64_linux/37/) [e/o](https://ci.adoptium.net/job/Grinder/9246/) | TBC
[aarch64](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk22/job/jdk22-linux-aarch64-temurin/24/artifact/workspace/target/OpenJDK22U-jdk_aarch64_linux_hotspot_2024-03-19-16-39.tar.gz) | 1 | [TBC](https://ci.adoptium.net/job/AQA_Test_Pipeline/225/) [s/o](https://ci.adoptium.net/job/Test_openjdk22_hs_sanity.openjdk_aarch64_linux/55/) [e/o](https://ci.adoptium.net/job/Grinder/9247/) | TBC
[x64](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk22/job/jdk22-linux-x64-temurin/43/artifact/workspace/target/OpenJDK22U-jdk_x64_linux_hotspot_2024-03-20-13-59.tar.gz) | 2 | [TBC](https://ci.adoptium.net/job/AQA_Test_Pipeline/229/) | TBC
[aarch64](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk22/job/jdk22-linux-aarch64-temurin/23/artifact/workspace/target/OpenJDK22U-jdk_aarch64_linux_hotspot_2024-03-19-16-08.tar.gz) | 2 | [TBC](https://ci.adoptium.net/job/AQA_Test_Pipeline/228/) | TBC
[x64](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk22/job/jdk22-linux-x64-temurin/42/artifact/workspace/target/OpenJDK22U-jdk_x64_linux_hotspot_2024-03-19-16-59.tar.gz) | 3 | [TBC](https://ci.adoptium.net/job/AQA_Test_Pipeline/222/) [s/o](https://ci.adoptium.net/job/Grinder/9244/) [e/o](https://ci.adoptium.net/job/Grinder/9249/) | TBC
[aarch64](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk22/job/jdk22-linux-aarch64-temurin/26/artifact/workspace/target/OpenJDK22U-jdk_aarch64_linux_hotspot_2024-03-20-13-56.tar.gz) | 3 | [TBC](https://ci.adoptium.net/job/AQA_Test_Pipeline/224/) [s/o](https://ci.adoptium.net/job/Grinder/9250/) [e/o](https://ci.adoptium.net/job/Grinder/9247/)| TBC

Initial AQA runs have been done but the openjdk set are being re-run due to them missing the testimage archive which caused a number of failures.

**Comment by sxa** [comment]
Noting that the `-W` options generate a significant amount of additional content in the logs. This is from the aarch64 builds:
```
$ grep -irw warning: jdk22w.none.log | cut -d: -f4-   | sort | uniq -c
      2 
      3  call to 'free' declared with attribute warning: use os::free [-Wattribute-warning]
      1  warning: call to 'calloc' declared with attribute warning: use os::malloc and zero out manually [-Wattribute-warning]
      2  warning: call to '_exit' declared with attribute warning: use os::exit [-Wattribute-warning]
      2  warning: call to 'exit' declared with attribute warning: use os::exit [-Wattribute-warning]
   1520  warning: call to 'free' declared with attribute warning: use os::free [-Wattribute-warning]
    740  warning: call to 'malloc' declared with attribute warning: use os::malloc [-Wattribute-warning]
     18  warning: call to 'posix_memalign' declared with attribute warning: don't use [-Wattribute-warning]
      7  warning: call to 'realloc' declared with attribute warning: use os::realloc [-Wattribute-warning]
      4  warning: call to 'realpath' declared with attribute warning: use os::Posix::realpath [-Wattribute-warning]
     29  warning: call to 'vsnprintf' declared with attribute warning: use os::vsnprintf [-Wattribute-warning]
      1  warning: 'jfr_event_writer_flush' violates the C++ One Definition Rule [-Wodr]
      1  warning: 'jfr_register_stack_filter' violates the C++ One Definition Rule [-Wodr]
      1  warning: 'jfr_type_id' violates the C++ One Definition Rule [-Wodr]
      1  warning: 'jfr_unregister_stack_filter' violates the C++ One Definition Rule [-Wodr]
      1  warning: 'memset' writing 696 bytes into a region of size 0 overflows the destination [-Wstringop-overflow=]
      1  warning: type of 'get_lwp_regs' does not match original declaration [-Wlto-type-mismatch]
      1  warning: type of 'init_libproc' does not match original declaration [-Wlto-type-mismatch]
sxa@fedora:~/bench/x$ 
```

**Comment by sxa** [comment]
I'm going to ignore that earlier table for now as there were some issues with those executions.
These are all run with:
- JDK_REPO=https://github.com/adoptium/jdk22u 
- JDK_BRANCH=jdk-22+35
- USE_TESTENV_PROPERTIES=false

Architecture | Job number | Options | sanity | extended | perf result | Comment
---|---|---|---|---|---|--
[x64](https://github.com/adoptium/temurin22-binaries/releases/download/jdk-22%2B35-ea-beta/OpenJDK22U-jdk_x64_linux_hotspot_22_35-ea.tar.gz) | 22+35-ea | None | G9768 | G9776 | | |
[aarch64](https://github.com/adoptium/temurin22-binaries/releases/download/jdk-22%2B35-ea-beta/OpenJDK22U-jdk_aarch64_linux_hotspot_22_35-ea.tar.gz) | 22+35-ea | None | G9769 | | | 
[x64](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk22/job/jdk22-linux-x64-temurin/38/artifact/workspace/target/OpenJDK22U-jdk_x64_linux_hotspot_2024-03-19-15-48.tar.gz) | 38 | RO | G9773 | | |
[aarch64](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk22/job/jdk22-linux-aarch64-temurin/24/artifact/workspace/target/OpenJDK22U-jdk_aarch64_linux_hotspot_2024-03-19-16-39.tar.gz) | 24 | RO | G9770 | G9777 | | |
[x64](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk22/job/jdk22-linux-x64-temurin/51/artifact/workspace/target/OpenJDK22U-jdk_x64_linux_hotspot_2024-04-13-10-52.tar.gz) | 51 | -cfi-vh | G9774 | | | |
[aarch64](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk22/job/jdk22-linux-aarch64-temurin/34/artifact/workspace/target/OpenJDK22U-jdk_aarch64_linux_hotspot_2024-04-13-11-42.tar.gz) | 34 | -cfi-vh | G9771 | G9778 | | |
[x64](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk22/job/jdk22-linux-x64-temurin/42/artifact/workspace/target/OpenJDK22U-jdk_x64_linux_hotspot_2024-03-19-16-59.tar.gz) | 42 | All | G9775 | | | |
[aarch64](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk22/job/jdk22-linux-aarch64-temurin/26/artifact/workspace/target/OpenJDK22U-jdk_aarch64_linux_hotspot_2024-03-20-13-56.tar.gz) | 26 | All | G9772 | G9779 | | |

**Comment by andrew-m-leonard** [comment]
> Noting that the `-W` options generate a significant amount of additional content in the logs. This is from the aarch64 builds:
> 
> ```
> $ grep -irw warning: jdk22w.none.log | cut -d: -f4-   | sort | uniq -c
>       2 
>       3  call to 'free' declared with attribute warning: use os::free [-Wattribute-warning]
>       1  warning: call to 'calloc' declared with attribute warning: use os::malloc and zero out manually [-Wattribute-warning]
>       2  warning: call to '_exit' declared with attribute warning: use os::exit [-Wattribute-warning]
>       2  warning: call to 'exit' declared with attribute warning: use os::exit [-Wattribute-warning]
>    1520  warning: call to 'free' declared with attribute warning: use os::free [-Wattribute-warning]
>     740  warning: call to 'malloc' declared with attribute warning: use os::malloc [-Wattribute-warning]
>      18  warning: call to 'posix_memalign' declared with attribute warning: don't use [-Wattribute-warning]
>       7  warning: call to 'realloc' declared with attribute warning: use os::realloc [-Wattribute-warning]
>       4  warning: call to 'realpath' declared with attribute warning: use os::Posix::realpath [-Wattribute-warning]
>      29  warning: call to 'vsnprintf' declared with attribute warning: use os::vsnprintf [-Wattribute-warning]
>       1  warning: 'jfr_event_writer_flush' violates the C++ One Definition Rule [-Wodr]
>       1  warning: 'jfr_register_stack_filter' violates the C++ One Definition Rule [-Wodr]
>       1  warning: 'jfr_type_id' violates the C++ One Definition Rule [-Wodr]
>       1  warning: 'jfr_unregister_stack_filter' violates the C++ One Definition Rule [-Wodr]
>       1  warning: 'memset' writing 696 bytes into a region of size 0 overflows the destination [-Wstringop-overflow=]
>       1  warning: type of 'get_lwp_regs' does not match original declaration [-Wlto-type-mismatch]
>       1  warning: type of 'init_libproc' does not match original declaration [-Wlto-type-mismatch]
> sxa@fedora:~/bench/x$ 
> ```

Yes, this is an awful lot of warnings!
Given it's usefulness, I won't try adding these extra -W flags

**Comment by andrew-m-leonard** [comment]
So the thoughts from talking to Andrew Haley, is the use of enhanced stack protector for Hotspot JVM stack is not beneficial as it is a private stack, and only serves to impinge performance.

**Comment by andrew-m-leonard** [comment]
Which does not leave any code options. If we feel any extra options are needed we should work with upstream to update.
